// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recommendations.Dictionaries.Infrastructure.DAL;

#nullable disable

namespace Recommendations.Dictionaries.Infrastructure.Migrations
{
    [DbContext(typeof(DictionariesDbContext))]
    [Migration("20260128210638_AddIsTrendingColumn")]
    partial class AddIsTrendingColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Dictionary")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.ArticleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SubCategoryId");

                    b.ToTable("ArticleTypes", "Dictionary");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.BaseColour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BaseColours", "Dictionary");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.MasterCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MasterCategories", "Dictionary");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseColourId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<bool>("IsBestseller")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Reviews")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleTypeId");

                    b.HasIndex("BaseColourId");

                    b.HasIndex("BrandName");

                    b.HasIndex("IsBestseller");

                    b.HasIndex("IsNew");

                    b.HasIndex("IsTrending");

                    b.HasIndex("Price");

                    b.HasIndex("Rating");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products", "Dictionary");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.ProductDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BodyOrGarmentSize")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Collar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Fabric")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SleeveLength")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Year")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Gender");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("Season");

                    b.HasIndex("Usage");

                    b.ToTable("ProductDetails", "Dictionary");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ImageType");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", "Dictionary");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MasterCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MasterCategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SubCategories", "Dictionary");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.ArticleType", b =>
                {
                    b.HasOne("Recommendations.Dictionaries.Core.Types.SubCategory", "SubCategory")
                        .WithMany("ArticleTypes")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.Product", b =>
                {
                    b.HasOne("Recommendations.Dictionaries.Core.Types.ArticleType", "ArticleType")
                        .WithMany()
                        .HasForeignKey("ArticleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recommendations.Dictionaries.Core.Types.BaseColour", "BaseColour")
                        .WithMany("Products")
                        .HasForeignKey("BaseColourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recommendations.Dictionaries.Core.Types.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticleType");

                    b.Navigation("BaseColour");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.ProductDetails", b =>
                {
                    b.HasOne("Recommendations.Dictionaries.Core.Types.Product", "Product")
                        .WithOne("Details")
                        .HasForeignKey("Recommendations.Dictionaries.Core.Types.ProductDetails", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.ProductImage", b =>
                {
                    b.HasOne("Recommendations.Dictionaries.Core.Types.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.SubCategory", b =>
                {
                    b.HasOne("Recommendations.Dictionaries.Core.Types.MasterCategory", "MasterCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MasterCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterCategory");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.BaseColour", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.MasterCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.Product", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Recommendations.Dictionaries.Core.Types.SubCategory", b =>
                {
                    b.Navigation("ArticleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
