// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Recommendations.VisualBased.Core.Data;

#nullable disable

namespace Recommendations.VisualBased.Core.Migrations
{
    [DbContext(typeof(VisualBasedDbContext))]
    [Migration("20260121194712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Visual")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recommendations.VisualBased.Core.Types.ItemVisual", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<Vector>("Emb")
                        .IsRequired()
                        .HasColumnType("vector(512)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.HasIndex("GeneratedAt");

                    b.ToTable("item_embeddings_visual", "Visual");
                });
#pragma warning restore 612, 618
        }
    }
}
