using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Recommendations.Tracking.Core.Migrations
{
    /// <inheritdoc />
    public partial class ChangeCfEmbeddingsDimTo128 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Truncate tables first (embeddings will be regenerated by training)
            migrationBuilder.Sql(@"TRUNCATE TABLE ""Tracking"".""user_embeddings_cf"";");
            migrationBuilder.Sql(@"TRUNCATE TABLE ""Tracking"".""item_embeddings_cf"";");

            // Change vector dimension from 768 to 128
            migrationBuilder.AlterColumn<string>(
                name: "Emb",
                schema: "Tracking",
                table: "user_embeddings_cf",
                type: "vector(128)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "vector(768)");

            migrationBuilder.AlterColumn<string>(
                name: "Emb",
                schema: "Tracking",
                table: "item_embeddings_cf",
                type: "vector(128)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "vector(768)");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Truncate tables first
            migrationBuilder.Sql(@"TRUNCATE TABLE ""Tracking"".""user_embeddings_cf"";");
            migrationBuilder.Sql(@"TRUNCATE TABLE ""Tracking"".""item_embeddings_cf"";");

            // Revert vector dimension from 128 to 768
            migrationBuilder.AlterColumn<string>(
                name: "Emb",
                schema: "Tracking",
                table: "user_embeddings_cf",
                type: "vector(768)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "vector(128)");

            migrationBuilder.AlterColumn<string>(
                name: "Emb",
                schema: "Tracking",
                table: "item_embeddings_cf",
                type: "vector(768)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "vector(128)");
        }
    }
}

