// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Recommendations.Tracking.Core.Data.Signals;

#nullable disable

namespace Recommendations.Tracking.Core.Migrations.SignalsDb
{
    [DbContext(typeof(SignalsDbContext))]
    [Migration("20260118163624_ChangeCfEmbeddingsDimTo128")]
    partial class ChangeCfEmbeddingsDimTo128
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tracking")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recommendations.Tracking.Core.Types.ItemEmbeddingCf", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<Vector>("Emb")
                        .IsRequired()
                        .HasColumnType("vector(128)");

                    b.Property<string>("ModelVer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TrainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItemId");

                    b.HasIndex("TrainedAt");

                    b.ToTable("item_embeddings_cf", "Tracking");
                });

            modelBuilder.Entity("Recommendations.Tracking.Core.Types.UserEmbeddingCf", b =>
                {
                    b.Property<string>("UserKey")
                        .HasColumnType("text");

                    b.Property<Vector>("Emb")
                        .IsRequired()
                        .HasColumnType("vector(128)");

                    b.Property<string>("ModelVer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TrainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserKey");

                    b.HasIndex("TrainedAt");

                    b.ToTable("user_embeddings_cf", "Tracking");
                });

            modelBuilder.Entity("Recommendations.Tracking.Core.Types.UserEmbeddingOnline", b =>
                {
                    b.Property<string>("UserKey")
                        .HasColumnType("text");

                    b.Property<Vector>("Emb")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserKey");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("user_embeddings_online", "Tracking");
                });

            modelBuilder.Entity("Recommendations.Tracking.Core.Types.UserItemInteraction", b =>
                {
                    b.Property<string>("UserKey")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .HasColumnType("text");

                    b.Property<int>("Carts")
                        .HasColumnType("integer");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastTs")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purchases")
                        .HasColumnType("integer");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("UserKey", "ItemId");

                    b.HasIndex("LastTs")
                        .HasDatabaseName("ix_uii_last_ts");

                    b.ToTable("user_item_interactions", "Tracking");
                });
#pragma warning restore 612, 618
        }
    }
}
